// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTjzwkgDwjV5h_9SLGc8bWXBrcIzgTxbE',
    appId: '1:229137920433:web:df6897159d8f36baa40d90',
    messagingSenderId: '229137920433',
    projectId: 'chatappw-92056',
    authDomain: 'chatappw-92056.firebaseapp.com',
    storageBucket: 'chatappw-92056.appspot.com',
    measurementId: 'G-5N80CDCFQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-wlc8ZDPDj-QHsFch1pYh6qgRJZw0Lwg',
    appId: '1:229137920433:android:ad51637b4dd7b283a40d90',
    messagingSenderId: '229137920433',
    projectId: 'chatappw-92056',
    storageBucket: 'chatappw-92056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9c_hFDKHuYry8Lo11jXauTV_AR8blcwQ',
    appId: '1:229137920433:ios:4a84d4b3c9c3fb95a40d90',
    messagingSenderId: '229137920433',
    projectId: 'chatappw-92056',
    storageBucket: 'chatappw-92056.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9c_hFDKHuYry8Lo11jXauTV_AR8blcwQ',
    appId: '1:229137920433:ios:4a84d4b3c9c3fb95a40d90',
    messagingSenderId: '229137920433',
    projectId: 'chatappw-92056',
    storageBucket: 'chatappw-92056.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD__8iuhLT--ttuMsv-6RaR8_uYvg_Hnro',
    appId: '1:229137920433:web:84bac216e2138977a40d90',
    messagingSenderId: '229137920433',
    projectId: 'chatappw-92056',
    authDomain: 'chatappw-92056.firebaseapp.com',
    storageBucket: 'chatappw-92056.appspot.com',
    measurementId: 'G-7RTR145X50',
  );
}
